[build]
  command = "npm run build"
  publish = ".next"

[env]
  [env.production]
    NEXT_PUBLIC_SITE_URL = "https://jack.thenas.us"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/config.yml"
  to = "/admin/config.yml"
  status = 200
